### ISSUE TITLE
Config colorScheme: 'dark' does nothing

### ISSUE THREAD

**Issue by jjxtra** [scaleflex/filerobot-image-editor#311]
`filerobot-image-editor v4.3.8`

I see references to a colorScheme config property. Has this been removed in the more recent versions? It appears to do nothing...

**Comment by jjxtra** [comment]
Looks like it was removed in 4.x versions. Have to make themes and use theme property. Dark/light theme included. There is additional work to do to style the css for popups and modals.

```js
const filerobot_dark_theme =
{
    palette:
    {
        'bg-secondary': '#222222',
        'bg-primary': '#111111',
        'bg-primary-active': '#333333',
        'accent-primary': '#DDDDDD',
        'accent-primary-active': '#FFFFFF',
        'icons-primary': '#CCCCCC',
        'icons-secondary': '#AAAAAA',
        'borders-primary': '#CCCCCC',
        'borders-secondary': '#AAAAAA',
        'borders-strong': '#FFFFFF',
        'light-shadow': '#111111',
        'warning': '#CC3333'
    },
    typography:
    {
        fontFamily: 'Arial'
    }
};

const filerobot_light_theme =
{
    palette:
    {
        'bg-secondary': '#DDDDDD',
        'bg-primary': '#EEEEEE',
        'bg-primary-active': '#CCCCCC',
        'accent-primary': '#222222',
        'accent-primary-active': '#000000',
        'icons-primary': '#333333',
        'icons-secondary': '#555555',
        'borders-primary': '#333333',
        'borders-secondary': '#555555',
        'borders-strong': '#000000',
        'light-shadow': '#DDDDDD',
        'warning': '#CC3333'
    },
    typography:
    {
        fontFamily: 'Arial'
    }
};
```

Styling for light/dark theme. My element id is `post-image-editor`. You can change to fit your element.

```css
#post-image-editor *,
.SfxModal-Wrapper *,
.SfxPopper-wrapper *
{
    color: #111111 !important;
}

#post-image-editor button,
.SfxModal-Wrapper button,
.SfxPopper-wrapper button
{
    background-color: unset !important;
    box-shadow: unset !important;
    border: 0.5px solid #777777 !important;
    border-radius: 4px !important;
}

#post-image-editor .FIE_topbar-close-button
{
    width: 24px;
    height: 24px;
    display: inline-block;
    padding: 3px 0 0 5px;
}

@media (prefers-color-scheme: dark)
{
    #post-image-editor *,
    .SfxModal-Wrapper *,
    .SfxPopper-wrapper *
    {
        color: #EEEEEE !important;
    }
}
```
